const questions = [
  {
    id: 1,
    difficulty: "easy",
    question: "RAG的全称是什么？",
    options: ["Retrieval-Augmented Generation", "Recurrent Attention Gradient", "Randomized Adaptive Gating", "Recursive Autoencoding Graph"],
    answer: 0,
  },
  {
    id: 2,
    difficulty: "easy",
    question: "RAG的主要目的是什么？",
    options: ["压缩模型参数量", "提升模型生成内容的准确性和时效性", "加速模型训练速度", "替代Transformer架构"],
    answer: 1,
  },
  {
    id: 3,
    difficulty: "easy",
    question: "在RAG中，“检索”通常针对什么进行？",
    options: ["模型的梯度", "外部知识库或文档集合", "输入图像的像素", "模型内部的注意力权重"],
    answer: 1,
  },
  {
    id: 4,
    difficulty: "easy",
    question: "下列哪个组件是RAG系统的核心？",
    options: ["检索器（Retriever）", "判别器（Discriminator）", "编码器（Encoder）仅", "池化层（Pooling）"],
    answer: 0,
  },
  {
    id: 5,
    difficulty: "easy",
    question: "RAG中的生成部分通常使用什么类型的模型？",
    options: ["卷积神经网络（CNN）", "循环神经网络（RNN）", "大语言模型（LLM）", "多层感知机（MLP）"],
    answer: 2,
  },
  {
    id: 6,
    difficulty: "easy",
    question: "检索器通常将文档和查询转换为哪种表示形式？",
    options: ["独热向量", "词袋模型", "稠密向量（嵌入）", "整数值索引"],
    answer: 2,
  },
  {
    id: 7,
    difficulty: "easy",
    question: "向量数据库在RAG中的作用是？",
    options: ["存储训练数据", "加速相似向量搜索", "生成文本", "执行梯度下降"],
    answer: 1,
  },
  {
    id: 8,
    difficulty: "easy",
    question: "下列哪个是常用的向量数据库？",
    options: ["MySQL", "PostgreSQL", "Pinecone", "Redis（仅键值）"],
    answer: 2,
  },
  {
    id: 9,
    difficulty: "easy",
    question: "RAG中常用的相似度度量不包括？",
    options: ["余弦相似度", "欧氏距离", "点积", "编辑距离"],
    answer: 3,
  },
  {
    id: 10,
    difficulty: "easy",
    question: "在RAG中，“上下文窗口”指的是什么？",
    options: ["检索到的文档数量", "生成模型一次能处理的最大token数", "向量索引的分片数", "训练时的批量大小"],
    answer: 1,
  },
  {
    id: 11,
    difficulty: "easy",
    question: "RAG通常用于解决LLM的什么问题？",
    options: ["过拟合", "幻觉（Hallucination）", "梯度消失", "训练速度慢"],
    answer: 1,
  },
  {
    id: 12,
    difficulty: "easy",
    question: "下列哪项是RAG的典型应用场景？",
    options: ["图像分类", "问答系统", "语音识别", "目标检测"],
    answer: 1,
  },
  {
    id: 13,
    difficulty: "easy",
    question: "RAG中的“知识库”通常由什么构成？",
    options: ["模型参数", "文本段落或文档", "图像特征", "音频波形"],
    answer: 1,
  },
  {
    id: 14,
    difficulty: "easy",
    question: "在检索阶段，用户输入被称为？",
    options: ["文档", "查询（Query）", "标签", "响应"],
    answer: 1,
  },
  {
    id: 15,
    difficulty: "easy",
    question: "将文档分割成更小片段（chunk）的主要目的是？",
    options: ["减少存储空间", "提高检索粒度和相关性", "增加模型参数量", "加密数据"],
    answer: 1,
  },
  {
    id: 16,
    difficulty: "easy",
    question: "稠密检索（Dense Retrieval）与传统稀疏检索（如BM25）的主要区别是？",
    options: ["稠密检索使用神经网络生成嵌入", "稠密检索速度更慢", "稀疏检索无法处理文本", "两者没有区别"],
    answer: 0,
  },
  {
    id: 17,
    difficulty: "easy",
    question: "RAG中“生成增强”的含义是？",
    options: ["对检索结果进行二次增强", "将检索到的信息作为额外输入提供给生成模型", "增强生成模型的训练数据", "增强向量索引"],
    answer: 1,
  },
  {
    id: 18,
    difficulty: "easy",
    question: "下列哪项不是RAG系统的输出？",
    options: ["生成的文本答案", "检索到的参考文档", "模型训练损失值", "引用来源"],
    answer: 2,
  },
  {
    id: 19,
    difficulty: "easy",
    question: "最简单的RAG流程是？",
    options: ["检索 → 生成", "生成 → 检索", "检索 → 重排 → 生成", "检索 → 检索 → 生成"],
    answer: 0,
  },
  {
    id: 20,
    difficulty: "easy",
    question: "嵌入模型（Embedding Model）的作用是？",
    options: ["将文本映射到固定维度的向量空间", "直接生成答案", "对答案进行排序", "压缩模型大小"],
    answer: 0,
  },
  {
    id: 21,
    difficulty: "easy",
    question: "哪个指标常用于评估检索结果的相关性？",
    options: ["BLEU", "ROUGE", "召回率（Recall）", "困惑度（Perplexity）"],
    answer: 2,
  },
  {
    id: 22,
    difficulty: "easy",
    question: "RAG与纯LLM生成相比，最大的优势是？",
    options: ["推理速度更快", "能够引用外部知识，减少幻觉", "无需训练数据", "参数量更小"],
    answer: 1,
  },
  {
    id: 23,
    difficulty: "easy",
    question: "在RAG中，“chunk大小”指的是？",
    options: ["每个文档片段的字符或token数量", "向量数据库的分区数量", "生成模型的最大输出长度", "检索返回的文档个数"],
    answer: 0,
  },
  {
    id: 24,
    difficulty: "easy",
    question: "下列哪个库常用于实现RAG的检索部分？",
    options: ["LangChain", "TensorFlow", "PyTorch", "OpenCV"],
    answer: 0,
  },
  {
    id: 25,
    difficulty: "easy",
    question: "RAG通常需要对知识库中的文档进行什么预处理？",
    options: ["分词、去除停用词、嵌入向量化", "图像增强", "音频降噪", "视频编码"],
    answer: 0,
  },
  {
    id: 26,
    difficulty: "easy",
    question: "当检索结果不相关时，生成模型最可能发生什么？",
    options: ["输出准确答案", "忽略检索内容，依赖自身知识", "产生幻觉或错误答案", "停止生成"],
    answer: 2,
  },
  {
    id: 27,
    difficulty: "easy",
    question: "在RAG中，“top-k检索”指的是？",
    options: ["返回最相似的k个文档片段", "只检索第k个文档", "使用k均值聚类", "检索k次"],
    answer: 0,
  },
  {
    id: 28,
    difficulty: "easy",
    question: "下列哪种嵌入模型常用于RAG？",
    options: ["BERT", "ResNet", "YOLO", "VGG"],
    answer: 0,
  },
  {
    id: 29,
    difficulty: "easy",
    question: "RAG的生成模型通常采用什么形式的输入？",
    options: ["仅查询", "仅检索到的文档", "查询 + 检索到的文档拼接", "随机噪声"],
    answer: 2,
  },
  {
    id: 30,
    difficulty: "easy",
    question: "更新RAG系统中的知识库，通常需要？",
    options: ["重新训练整个生成模型", "重新计算新文档的嵌入并插入向量库", "修改模型参数", "重启数据库服务"],
    answer: 1,
  },
  {
    id: 31,
    difficulty: "easy",
    question: "下列哪个是RAG中生成模型的常用基座？",
    options: ["GPT系列", "LeNet", "AlexNet", "U-Net"],
    answer: 0,
  },
  {
    id: 32,
    difficulty: "easy",
    question: "为什么需要将文档分块（chunking）？",
    options: ["避免超出LLM的上下文窗口限制", "提高检索速度", "降低存储成本", "防止过拟合"],
    answer: 0,
  },
  {
    id: 33,
    difficulty: "easy",
    question: "在RAG中，“索引（Index）”指的是？",
    options: ["文档片段的向量化存储结构", "数据库的主键", "模型的层索引", "训练迭代次数"],
    answer: 0,
  },
  {
    id: 34,
    difficulty: "easy",
    question: "以下哪个操作发生在RAG的生成阶段之前？",
    options: ["答案校对", "相似度排序", "输出采样", "损失计算"],
    answer: 1,
  },
  {
    id: 35,
    difficulty: "easy",
    question: "RAG不适用于哪种任务？",
    options: ["开放域问答", "事实核查", "图像分割", "文档摘要"],
    answer: 2,
  },
  {
    id: 36,
    difficulty: "easy",
    question: "检索器的训练通常使用什么损失函数？",
    options: ["对比损失（Contrastive Loss）", "交叉熵损失（仅分类）", "均方误差", "铰链损失（Hinge Loss）"],
    answer: 0,
  },
  {
    id: 37,
    difficulty: "easy",
    question: "以下哪种技术可以提升检索速度？",
    options: ["使用近似最近邻（ANN）索引", "增加文档chunk大小", "使用更深的嵌入模型", "禁用缓存"],
    answer: 0,
  },
  {
    id: 38,
    difficulty: "easy",
    question: "RAG中的“引用”通常指？",
    options: ["模型参数的来源", "生成答案所依据的检索文档片段", "训练数据集的引用", "代码库的引用"],
    answer: 1,
  },
  {
    id: 39,
    difficulty: "easy",
    question: "下面哪个是RAG的变体？",
    options: ["RAG-Sequence", "RAG-Token", "两者都是", "两者都不是"],
    answer: 2,
  },
  {
    id: 40,
    difficulty: "easy",
    question: "RAG-Sequence和RAG-Token的主要区别在于？",
    options: ["检索发生的粒度（整个序列还是每个token）", "使用的生成模型不同", "嵌入维度不同", "知识库类型不同"],
    answer: 0,
  },
  {
    id: 41,
    difficulty: "easy",
    question: "在RAG中，“稠密检索”相比“稀疏检索”的缺点可能是？",
    options: ["无法捕捉语义", "需要大量计算资源来训练嵌入模型", "不支持文本", "速度极慢"],
    answer: 1,
  },
  {
    id: 42,
    difficulty: "easy",
    question: "以下哪个不是RAG的评估维度？",
    options: ["答案准确性", "检索召回率", "模型参数量", "生成流畅度"],
    answer: 2,
  },
  {
    id: 43,
    difficulty: "easy",
    question: "在LangChain框架中，实现RAG通常需要组合哪些模块？",
    options: ["TextLoader, VectorStore, LLM", "Conv2D, MaxPool2D, Linear", "LSTM, GRU, Attention", "TransformerEncoder, PositionalEncoding"],
    answer: 0,
  },
  {
    id: 44,
    difficulty: "easy",
    question: "当知识库非常庞大时，全量扫描检索的复杂度是？",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    answer: 2,
  },
  {
    id: 45,
    difficulty: "easy",
    question: "近似最近邻（ANN）检索相比精确检索牺牲了什么？",
    options: ["召回率", "存储空间", "查询灵活性", "支持的数据类型"],
    answer: 0,
  },
  {
    id: 46,
    difficulty: "easy",
    question: "RAG中的“HyDE”方法是？",
    options: ["对查询进行假设性文档生成后再检索", "对文档进行超维编码", "混合密度估计", "动态上下文扩展"],
    answer: 0,
  },
  {
    id: 47,
    difficulty: "easy",
    question: "以下哪个是RAG的典型挑战？",
    options: ["检索结果与生成模型内部知识冲突", "无法处理长文本", "不支持多模态", "需要GPU训练"],
    answer: 0,
  },
  {
    id: 48,
    difficulty: "easy",
    question: "在RAG中，“重排序（Re-ranking）”的作用是？",
    options: ["改变检索器的训练目标", "对初步检索结果进行更精细的相关性排序", "重新生成查询", "压缩文档长度"],
    answer: 1,
  },
  {
    id: 49,
    difficulty: "easy",
    question: "检索器的召回率低会导致？",
    options: ["生成答案缺乏必要的支持信息", "生成模型过度自信", "检索速度变慢", "向量库损坏"],
    answer: 0,
  },
  {
    id: 50,
    difficulty: "easy",
    question: "下列哪个是RAG系统的输入？",
    options: ["用户问题", "模型权重", "训练标签", "损失函数"],
    answer: 0,
  },
  {
    id: 51,
    difficulty: "medium",
    question: "在RAG中，如果检索到的文档与查询高度相关但答案错误，问题最可能出在？",
    options: ["嵌入模型", "生成模型的理解或推理能力", "向量索引结构", "文档分块大小"],
    answer: 1,
  },
  {
    id: 52,
    difficulty: "medium",
    question: "以下哪种策略能有效缓解“中间丢失”现象（Lost in the Middle）？",
    options: ["将检索到的文档按相关性重新排序，最相关的放在上下文两端", "增加生成的温度参数", "使用更大的嵌入维度", "减少检索文档数量"],
    answer: 0,
  },
  {
    id: 53,
    difficulty: "medium",
    question: "针对RAG的“查询重写”（Query Rewriting）技术的主要目的是？",
    options: ["将用户问题改写成更适合检索的形式", "压缩查询长度", "加密查询内容", "增加查询的随机性"],
    answer: 0,
  },
  {
    id: 54,
    difficulty: "medium",
    question: "下列哪种方法属于“主动检索”（Active Retrieval）？",
    options: ["在生成过程中多次调用检索器", "预先缓存所有可能的查询结果", "使用固定的检索阈值", "只检索一次"],
    answer: 0,
  },
  {
    id: 55,
    difficulty: "medium",
    question: "评估RAG生成答案的“忠实度”（Faithfulness）是指？",
    options: ["答案是否完全来自检索到的文档", "答案的语法正确性", "答案的长度符合要求", "答案是否包含数学公式"],
    answer: 0,
  },
  {
    id: 56,
    difficulty: "medium",
    question: "以下哪个指标不适合评估RAG的检索质量？",
    options: ["MRR（Mean Reciprocal Rank）", "NDCG（Normalized Discounted Cumulative Gain）", "BLEU", "Hit Rate"],
    answer: 2,
  },
  {
    id: 57,
    difficulty: "medium",
    question: "在RAG中，使用“滑动窗口分块”（Sliding Window Chunking）的好处是？",
    options: ["保留段落间的上下文重叠", "减少存储空间", "加速检索", "防止过拟合"],
    answer: 0,
  },
  {
    id: 58,
    difficulty: "medium",
    question: "当使用LLM作为生成器时，增加检索到的文档数量（如从5增加到20）可能带来的问题是？",
    options: ["超出LLM的上下文窗口", "检索延迟降低", "答案准确性必然提升", "嵌入维度需增加"],
    answer: 0,
  },
  {
    id: 59,
    difficulty: "medium",
    question: "下列哪项技术可以用于RAG中减少重复的检索计算？",
    options: ["结果缓存（Cache）", "数据增强", "学习率衰减", "梯度裁剪"],
    answer: 0,
  },
  {
    id: 60,
    difficulty: "medium",
    question: "“自我反思”（Self-RAG）的特点是什么？",
    options: ["模型在生成过程中评估检索是否需要以及是否相关", "模型对自己的输出进行语法检查", "模型训练时使用对抗样本", "模型生成多个答案后投票"],
    answer: 0,
  },
  {
    id: 61,
    difficulty: "medium",
    question: "在RAG系统中，优化“检索-生成”协同的策略不包括？",
    options: ["联合微调解码器和检索器", "使用强化学习调整检索器的阈值", "增加生成模型的层数", "训练一个适配器来重新加权检索结果"],
    answer: 2,
  },
  {
    id: 62,
    difficulty: "medium",
    question: "针对多模态RAG，下列描述正确的是？",
    options: ["检索的文档只能包含文本", "可以使用多模态嵌入（如CLIP）进行图文联合检索", "生成模型必须是多模态的", "图像不能作为检索源"],
    answer: 1,
  },
  {
    id: 63,
    difficulty: "medium",
    question: "在评估RAG系统时，“上下文相关性”（Context Relevance）指的是？",
    options: ["检索到的文档是否与查询相关", "生成答案是否流畅", "系统响应时间是否短", "向量索引是否紧凑"],
    answer: 0,
  },
  {
    id: 64,
    difficulty: "medium",
    question: "RAG中“文档打包”（Document Packing）技术用于？",
    options: ["将多个检索片段合并成一个适合LLM输入的格式", "压缩文档以节省存储", "加密文档内容", "对文档进行去重"],
    answer: 0,
  },
  {
    id: 65,
    difficulty: "medium",
    question: "以下哪种情况最适合使用RAG而不是微调LLM？",
    options: ["知识频繁更新且需要低延迟", "固定领域的少量私有数据", "模型需要学习新的语言风格", "训练数据充足且任务单一"],
    answer: 0,
  },
  {
    id: 66,
    difficulty: "medium",
    question: "“重排序模型”通常比嵌入检索器更准确但更慢，因此常被用于？",
    options: ["作为第一级检索", "对初步检索的少量候选进行精细排序", "替代向量数据库", "用于训练嵌入模型"],
    answer: 1,
  },
  {
    id: 67,
    difficulty: "medium",
    question: "在RAG中，稀疏检索器（如BM25）和稠密检索器混合使用的主要好处是？",
    options: ["同时利用关键词匹配和语义相似性", "降低计算复杂度", "简化系统架构", "避免使用向量数据库"],
    answer: 0,
  },
  {
    id: 68,
    difficulty: "medium",
    question: "下列哪个不是RAG中常见的查询优化方法？",
    options: ["查询扩展（Query Expansion）", "查询分解（Query Decomposition）", "查询加密（Query Encryption）", "假想文档生成（HyDE）"],
    answer: 2,
  },
  {
    id: 69,
    difficulty: "medium",
    question: "对于RAG系统，知识库版本更新的最佳实践是？",
    options: ["完全重建向量索引", "增量更新嵌入并维护两个索引", "每次重新训练生成模型", "忽略旧文档"],
    answer: 1,
  },
  {
    id: 70,
    difficulty: "medium",
    question: "RAG中的“路由”（Routing）是指？",
    options: ["根据查询类型选择不同的检索源或处理流程", "网络数据包传输", "向量数据库的分片策略", "生成模型的采样策略"],
    answer: 0,
  },
  {
    id: 71,
    difficulty: "medium",
    question: "以下哪个开源框架专门为RAG的评估设计？",
    options: ["RAGAS", "TensorBoard", "Weights & Biases", "MLflow"],
    answer: 0,
  },
  {
    id: 72,
    difficulty: "medium",
    question: "RAGAS评估框架中，“答案相关性”（Answer Relevance）主要通过什么方式计算？",
    options: ["让LLM生成问题并与原查询比较", "计算BLEU分数", "人工标注", "向量距离"],
    answer: 0,
  },
  {
    id: 73,
    difficulty: "medium",
    question: "当检索到的文档包含相互矛盾的信息时，生成模型应该？",
    options: ["忽略所有文档", "基于自身知识选择一种", "指出矛盾并尝试给出最可信答案", "只选择第一段"],
    answer: 2,
  },
  {
    id: 74,
    difficulty: "medium",
    question: "在RAG中，“上下文学习”（In-Context Learning）是指？",
    options: ["通过检索到的示例指导LLM生成", "在上下文中训练模型", "动态调整上下文窗口大小", "检索模型的上下文表示"],
    answer: 0,
  },
  {
    id: 75,
    difficulty: "medium",
    question: "以下哪个技术可以缓解RAG中由于分块导致的答案跨块问题？",
    options: ["父文档检索（Parent Document Retriever）", "增大块尺寸", "减少检索数量", "使用更小的嵌入模型"],
    answer: 0,
  },
  {
    id: 76,
    difficulty: "medium",
    question: "对于延迟敏感的RAG应用，下列优化最有效的是？",
    options: ["使用量化后的嵌入模型和ANN索引", "增加生成模型的参数", "提高检索的top-k值", "使用更复杂的重排序模型"],
    answer: 0,
  },
  {
    id: 77,
    difficulty: "medium",
    question: "“记忆型RAG”（Memory RAG）相对于基础RAG增加了什么？",
    options: ["外部记忆模块用于跨会话信息存储", "更大的模型参数", "更多的训练数据", "图像处理能力"],
    answer: 0,
  },
  {
    id: 78,
    difficulty: "medium",
    question: "下列哪个选项正确描述了RAG中的“递归检索”（Recursive Retrieval）？",
    options: ["根据初始检索结果生成新查询并再次检索", "递归地分割文档", "递归地训练检索器", "递归地生成答案"],
    answer: 0,
  },
  {
    id: 79,
    difficulty: "medium",
    question: "针对结构化数据（如表格），RAG的检索通常需要？",
    options: ["将表格序列化成文本或使用特殊嵌入方法", "无法处理结构化数据", "转换为图像", "使用关系数据库代替向量库"],
    answer: 0,
  },
  {
    id: 80,
    difficulty: "medium",
    question: "评估RAG生成答案的“噪声鲁棒性”（Noise Robustness）的方法是？",
    options: ["在检索结果中加入随机不相关文档，观察答案质量下降程度", "测量答案的长度", "计算生成时间", "检查是否存在语法错误"],
    answer: 0,
  },
  {
    id: 81,
    difficulty: "hard",
    question: "在“修正检索增强生成”（Corrective RAG）中，当检测到检索文档与查询相关性低时，系统会？",
    options: ["放弃检索并直接使用LLM生成", "触发网络搜索或备用检索源", "增加温度参数重新生成", "降低阈值重复检索"],
    answer: 1,
  },
  {
    id: 82,
    difficulty: "hard",
    question: "假设生成模型为7B参数LLM，上下文窗口为4096 token，每个文档块约500 token。为了保证生成答案时还能容纳至少256 token的输出，最多能检索多少个块？",
    options: ["约8个", "约16个", "约4个", "约7个"],
    answer: 3,
  },
  {
    id: 83,
    difficulty: "hard",
    question: "在RAG中，使用“知识蒸馏”来压缩检索器的主要挑战是？",
    options: ["保持双编码器（查询和文档）的对齐能力", "蒸馏后的模型无法处理长文本", "蒸馏会导致检索精度必然下降", "蒸馏只适用于生成模型"],
    answer: 0,
  },
  {
    id: 84,
    difficulty: "hard",
    question: "下列哪种情况最可能导致RAG的“反链式幻觉”（Anti-chain Hallucination）？",
    options: ["检索到的文档与LLM内部知识强烈冲突，LLM拒绝遵从", "检索结果完全正确但LLM忽略", "查询过于模糊", "知识库过时"],
    answer: 0,
  },
  {
    id: 85,
    difficulty: "hard",
    question: "在“自适应检索”（Adaptive Retrieval）策略中，模型如何决定是否需要进行检索？",
    options: ["基于对自身知识置信度的评估", "总是检索", "从不检索", "随机决定"],
    answer: 0,
  },
  {
    id: 86,
    difficulty: "hard",
    question: "假设你想让RAG系统支持百万级文档的实时更新（每秒数十个新文档），以下哪个索引方案最合适？",
    options: ["基于HNSW的向量索引并支持增量插入", "全量重建的IVF索引", "基于磁盘的FLAT索引", "不使用索引，每次线性扫描"],
    answer: 0,
  },
  {
    id: 87,
    difficulty: "hard",
    question: "针对RAG的“主动学习”用于改进检索器时，通常选择哪些样本进行标注？",
    options: ["模型最不确定的查询-文档对", "随机抽取的样本", "最容易的样本", "最长的文档"],
    answer: 0,
  },
  {
    id: 88,
    difficulty: "hard",
    question: "以下哪个损失函数设计最适用于联合训练RAG的检索器和生成器？",
    options: ["检索器的对比损失 + 生成器的负对数似然，通过加权和联合优化", "只优化生成器的交叉熵", "只优化检索器的三元组损失", "对抗损失"],
    answer: 0,
  },
  {
    id: 89,
    difficulty: "hard",
    question: "在RAG中，如果检索器使用BERT-based的稠密编码器，而生成器使用GPT，如何解决嵌入空间不一致的问题？",
    options: ["在生成器输入前加一个可训练的适配器层", "强制两者使用相同的tokenizer", "冻结检索器", "使用余弦相似度代替点积"],
    answer: 0,
  },
  {
    id: 90,
    difficulty: "hard",
    question: "对于需要处理私有数据且不能将数据发送到外部API的RAG系统，以下哪个部署方案最合适？",
    options: ["完全本地部署，使用开源的LLM和向量数据库", "使用云提供商的托管RAG服务", "使用闭源商业LLM API", "不部署RAG，仅用本地关键词搜索"],
    answer: 0,
  },
  {
    id: 91,
    difficulty: "hard",
    question: "“迭代RAG”（Iterative RAG）与“自适应RAG”的区别是？",
    options: ["迭代RAG固定多轮检索，自适应根据置信度动态决定", "迭代RAG每次检索相同数量文档", "自适应RAG无法处理复杂问题", "两者没有区别"],
    answer: 0,
  },
  {
    id: 92,
    difficulty: "hard",
    question: "评估RAG系统时，如果生成答案完全正确但未引用任何检索文档（即完全来自LLM内部知识），下列哪个指标会较低？",
    options: ["忠实度（Faithfulness）", "答案准确性（Answer Accuracy）", "检索召回率（Retrieval Recall）", "生成流畅度"],
    answer: 0,
  },
  {
    id: 93,
    difficulty: "hard",
    question: "在RAG中，使用“最大边际相关性”（MMR, Maximum Marginal Relevance）进行重排序的目的主要是？",
    options: ["在相关性和多样性之间平衡，避免冗余", "最大化相关性", "最小化计算开销", "确保排序稳定"],
    answer: 0,
  },
  {
    id: 94,
    difficulty: "hard",
    question: "以下哪个策略可以最有效地减少RAG的“检索延迟”同时保持高召回率？",
    options: ["使用多阶段检索：粗排ANN + 精排小模型", "增加HNSW的ef_construction参数", "使用全精确检索", "将向量维度提升到4096"],
    answer: 0,
  },
  {
    id: 95,
    difficulty: "hard",
    question: "假设生成模型是经过RLHF训练的，直接将其用于RAG可能出现什么新问题？",
    options: ["模型可能更倾向于输出有用但虚构的内容，而不是依赖检索到的知识", "模型无法处理长上下文", "检索器与生成器不兼容", "推理速度显著下降"],
    answer: 0,
  },
  {
    id: 96,
    difficulty: "hard",
    question: "对于多跳问题（Multi-hop QA），传统单次RAG往往效果不佳，以下哪种改进最有效？",
    options: ["链式检索（Chain-of-Retrieval）或基于图的检索", "增大块大小", "减少检索文档数量", "使用更大的嵌入模型"],
    answer: 0,
  },
  {
    id: 97,
    difficulty: "hard",
    question: "在RAG的评估中，使用LLM-as-a-Judge来评估答案质量时，主要挑战是？",
    options: ["Judge模型本身可能具有偏见或与待评估模型同源", "成本过高", "无法处理长答案", "速度太慢"],
    answer: 0,
  },
  {
    id: 98,
    difficulty: "hard",
    question: "以下哪种RAG架构最适合处理需要实时更新知识的场景，且每次查询成本敏感？",
    options: ["冻结的检索器和生成器，只更新向量库", "每天微调生成模型", "不使用检索，仅用长上下文LLM", "混合使用BM25和LLM rerank"],
    answer: 0,
  },
  {
    id: 99,
    difficulty: "hard",
    question: "“CRAG”（Corrective RAG）中，用于评估检索文档相关性的“轻量级评估器”通常如何训练？",
    options: ["使用相关性标注数据，训练一个二分类器（如BERT）", "使用生成模型自身评分", "人工规则", "无监督聚类"],
    answer: 0,
  },
  {
    id: 100,
    difficulty: "hard",
    question: "给定一个RAG系统，检索召回率接近100%，但答案准确率仅60%，最不可能的原因是？",
    options: ["生成模型能力不足", "检索到的文档中包含大量噪声或矛盾信息", "用户查询过于模糊", "向量索引内存不足"],
    answer: 3,
  },
];

module.exports = questions;
